### ISSUE TITLE
question: 0 | 0

### ISSUE THREAD

**Issue by missinglink** [lemire/FastBitSet.js#21]
Hi Daniel,

Apologies for opening an issue for this as it's more of a question for which I wasn't able to find an answer online.
In this code you use an unusual convention of initialising variables with `0 | 0`, [example](https://github.com/lemire/FastBitSet.js/blob/master/FastBitSet.js#L170)

What is the purpose of this? I'm assuming it has a performance benefit but I can't imagine what since it seems unintuitive to me.

Please feel free to close this issue 🙏 

Kind Regards
Peter

**Comment by lemire** [comment]
By default, numbers in javascript are binary64 numbers (floating-point numbers). We want to the the JavaScript compiler that our numbers are integers. The operator | returns returns a 32-bit integer, by definition.

**Comment by missinglink** [comment]
Thanks for your response, makes sense but I wasn't aware that *internally* JS engines had multiple different numeric types as they are not exposed to the user.

Are you able to recommend some reading material which covers this topic where I can learn more without digging through the source code of V8 or whatever?

**Comment by lemire** [comment]
It would be best to raise the issue with the v8 community if v8 is your target. Generally speaking, the documentation of the behaviour of the JavaScript engine should be under the responsibility of the engine itself.
