### ISSUE TITLE
maybe bug?

### ISSUE THREAD

**Issue by dabba39** [lemire/FastBitSet.js#5]
https://github.com/lemire/FastBitSet.js/blob/fca0d87b4728c0489e8fb5d0a93195689d886ae7/FastBitSet.js#L108

Shouldn't it exit, if the item is not 0?

**Comment by lemire** [comment]
Yes, it is surely a bug. 

To be fixed.

**Comment by lemire** [comment]
Fixed with accompanying unit test.
